### ISSUE TITLE
How does get_stats handle players with uncommon names?

### ISSUE THREAD

**Issue by adoreste319** [vishaalagartha/basketball_reference_scraper#12]
When I try getting Dario Šarić's stats, I get the following error:

Traceback (most recent call last):
  File "C:\Users\Alexis\Downloads\winter2020\eecs497\algo.py", line 37, in <module>
    print(get_stats("Dario Šarić"))
  File "C:\Program Files\Python38\Lib\site-packages\basketball_reference_scraper\players.py", line 11, in get_stats
    suffix = get_player_suffix(name).replace('/', '%2F')
AttributeError: 'NoneType' object has no attribute 'replace'

What format do names have to be in?

**Comment by adoreste319** [comment]
The same happens for players like Nikola Vučević, Ante Žižić, Nenê Hilário, etc. A potential fix could be to let users input the html playerID basketball reference uses, since this string's format is standardized. For example, every bball ref link ends in /LLLLLFFNN.html. Let me know what you think!

**Comment by adoreste319** [comment]
Nevermind, had a deprecated version of the scraper, just updated to 1.0.6 and it works like a charm!

**Comment by adoreste319** [comment]
Fixed it! Looks like in utils.py in the second function, you set the player's last name to lowercase without accounting for whether their names contain accents (which cannot be used to construct the basketball reference link). My fix is crude, but I basically change every instance of a special character with its un-accented lowercase character.
