### ISSUE TITLE
No module named 'constants'

### ISSUE THREAD

**Issue by vincentyliu2001** [vishaalagartha/basketball_reference_scraper#37]
Note: I just installed this and had to install lxml with lxml-4.4.2-cp37-cp37m-win_amd64.whl using pip install manually. 
Here is the traceback, it seems like it can't find constants.py for some reason:
```
Traceback (most recent call last):
  File "C:\Users\yishi\PycharmProjects\baksetball-algo\venv\lib\site-packages\basketball_reference_scraper\teams.py", line 6, in <module>
    from constants import TEAM_TO_TEAM_ABBR, TEAM_SETS
ModuleNotFoundError: No module named 'constants'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/yishi/PycharmProjects/baksetball-algo/scraper.py", line 1, in <module>
    from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats, get_team_misc
  File "C:\Users\yishi\PycharmProjects\baksetball-algo\venv\lib\site-packages\basketball_reference_scraper\teams.py", line 10, in <module>
    from basketball_reference_scraper.utils import remove_accents
  File "C:\Users\yishi\PycharmProjects\baksetball-algo\venv\lib\site-packages\basketball_reference_scraper\utils.py", line 4, in <module>
    import unicodedata, unidecode
ModuleNotFoundError: No module named 'unidecode'

**Comment by vincentyliu2001** [comment]
apparently unidecode wasn't installed properly, I ran ```pip install Unidecode``` and that seems to have fixed the issue.
