### ISSUE TITLE
team roster per 36 values missing

### ISSUE THREAD

**Issue by adoreste319** [vishaalagartha/basketball_reference_scraper#6]
After fiddling around with the web scraper for a while, I noticed that while using the get_roster_stats function, setting the data format variable to 'PER_36' returns the following:

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    get_roster_stats('GSW', 2019, 'PER_36', False)
  File "C:\Program Files\Python38\Lib\site-packages\basketball_reference_scraper\teams.py", line 98, in get_roster_stats
    df2 = pd.read_html(str(table))[0]
  File "C:\Program Files\Python38\Lib\site-packages\pandas\io\html.py", line 1090, in read_html
    return _parse(
  File "C:\Program Files\Python38\Lib\site-packages\pandas\io\html.py", line 912, in _parse
    raise_with_traceback(retained)
  File "C:\Program Files\Python38\Lib\site-packages\pandas\compat\__init__.py", line 47, in raise_with_traceback
    raise exc.with_traceback(traceback)
ValueError: No tables found

However, it is well known that basketball-reference indeed has these statistics on their website--is there a fix for this?

**Comment by vishaalagartha** [comment]
Sorry, you're right that PER_36 stats are easily available. However, the selector is `PER_MINUTE` not `PER_36`. Try this snippet:

```
from basketball_reference_scraper.teams import get_roster_stats
get_roster_stats('GSW', 2019, 'PER_MINUTE', False)
```
That should work. This was an issue in the documentation that is now fixed.

Thanks!

**Comment by adoreste319** [comment]
Thank you! Overall, best bball reference API I've seen, great job!
